color0 #2e231b
color1 #c0442b
color2 #8a9a5b
color3 #d89a5b
color4 #6f8da0
color5 #b06a78
color6 #7fa89a
color7 #e6d6cb
color8 #594636
color9 #e0563b
color10 #a8b56e
color11 #f0b85e
color12 #8fa9bb
color13 #d08a96
color14 #9fc3b4
color15 #fff6f0
background #1c120c
selection_foreground #fff6f0
cursor #e0563b
cursor_text_color #1c120c
foreground #e6d6cb
selection_background #283457
active_border_color #7aa2f7
inactive_border_color #bb9af7

active_tab_foreground   #16161e
active_tab_background   #7aa2f7
inactive_tab_foreground #9aa5ce
inactive_tab_background #24283b
cursor_trail_color      #9aa5ce
